### ISSUE TITLE
Sozial Apps 

### ISSUE THREAD

**Issue by Packetfahrer** [angelXwind/PreferenceOrganizer2#14]
Social Apps (Facebook, Twitter )  are in the Section Tweak´s on iPad Air2 iOS 9.1.

**Comment by PoomSmart** [comment]
@Packetfahrer I think this bug is in PreferenceLoader itself, it just need to be updated.

**Comment by angelXwind** [comment]
No longer relevant as this has since been fixed in the latest version.
