### ISSUE TITLE
Better URL support

### ISSUE THREAD

**Issue by kirb** [angelXwind/PreferenceOrganizer2#3]
Previously just checking for PreferenceOrganizer.dylib and opening `prefs:root=Cydia&path=TypeStatus` was fine, but with PO2 `prefs:root=Tweaks&path=TypeStatus` goes to the tweaks controller instead of TypeStatus. Plus that won't even happen if the section is renamed.

I'd say PreferenceOrganizer should hook URL opens (`-[PreferencesAppController applicationOpenURL:]` if I recall correctly) and change URLs of the format `prefs:root=Cydia&path=TypeStatus` and `prefs:root=TypeStatus` to whatever is appropriate.

**Comment by angelXwind** [comment]
As of commit `51f7da34574535c08df1a122dfe68cd709dbd4cc`, this is now implemented.

**Comment by kirb** [comment]
👍
