### ISSUE TITLE
Social Networking Apps erroneously appear in Tweak specifier (iOS 10.2)

### ISSUE THREAD

**Issue by breakingDarko** [angelXwind/PreferenceOrganizer2#30]
I'm using the 3.7 version on an IPad Air running iOS 10.2 
The social networking apps keep getting listed on the Tweak list, tried reinstalling but without succes.
On my IPhone 5S running iOS 10.2 your tweak worked like a charme.
I really appreciate the work you have been doing for us, thank you for your time.

**Comment by angelXwind** [comment]
Closing as the issue has been fixed and will be included in the next update release.
