### ISSUE TITLE
"Wallet and Apple Pay" specifier appears in both System Apps and the main settings (iOS 10.2)

### ISSUE THREAD

**Issue by A1p1n3** [angelXwind/PreferenceOrganizer2#31]
The Wallet and Apple Pay tab are below the "App Store" tab after an update of PO2 (Current version is 3.7)

**Comment by angelXwind** [comment]
What iOS version and device is this happening on?

**Comment by A1p1n3** [comment]
This was happening on iOS 10.1.1 on an iPhone 7. I am no longer jail broken but this issue seemed to happen after 
1. Wallet was opened for Apple Pay 
2. After closing setting via app switcher in the wallet or App Store category 

(This may be an isolated issue)

**Comment by reds0ul** [comment]
Happend to me aswell, occurred on random opens 

iPhone 6S
10.2

**Comment by kr0n1k** [comment]
Happens on 10.2 6+ here. When scrolling down it will be spaced away from the AppStore section for a second then joins the block of sections.

**Comment by angelXwind** [comment]
Bug is fixed as of version 4.x.
