### ISSUE TITLE
Crash occurs when Preferences is opened, backgrounded, and opened again (iOS 10.2)

### ISSUE THREAD

**Issue by auboli77** [angelXwind/PreferenceOrganizer2#32]
Usual when they are running in the background and you try to open the app.

I am using PreferenceOrganizer2 v3.7.

I got this logs from a tweak CrashReporter.
Crash log: [Link](https://gist.github.com/auboli77/227f85d6be83fece258b502e0fdfe07c)
Syslog: [Link](https://gist.github.com/auboli77/eeba4d03c8a96e9533560fe871f2b3e6)

**Comment by angelXwind** [comment]
Closing as the issue has been fixed and will be included in the next update release.
