### ISSUE TITLE
Preferences not always written to disk!? Seems like a KarenPrefs bug. (iOS 10.1.1)

### ISSUE THREAD

**Issue by maortega89** [angelXwind/PreferenceOrganizer2#33]
Happens about 1-3x per day, since installing. Also settings within preference organizer 2 don't always save and have to go back to "apply and quit" app.

Crash log: https://docs.google.com/document/d/126jv1vJtldcclJyrpJKDBgrUIlRekD4JKFCJ-LHAIsk

Syslog: https://docs.google.com/document/d/133qSdoACy8-A3s9ddVVbu85Dk1_poZAnGxTHk8zxDSA

**Comment by angelXwind** [comment]
Closing as the issue has been fixed and will be included in the next update release.
