### ISSUE TITLE
FaceTime and iMessages randomly appear in original position and also get duplicated underneath OrganisedSpecifiers (iOS 9.3.3; 10.2)

### ISSUE THREAD

**Issue by aiyerp** [angelXwind/PreferenceOrganizer2#34]
At the first setting, all are okay. Later from nowhere, FaceTime appears in default position AND under PreferenceOrganizer. Maybe iMessages too at times. But mostly FaceTime. 

Devices with the above issue: 
iPhone 6S(iOS 9.3.3) - Sometimes it goes to safe mode besides the above issue. 
iPhone 6S (iOS 10.2) - No safe mode issue. 

Verified even with ONLY PO2 installed.

**Comment by angelXwind** [comment]
I'm completely unable to reproduce this — do you have any more information about this bug?

**Comment by angelXwind** [comment]
Closed due to inactivity. Feel free to reopen at any time.
