### ISSUE TITLE
Specifiers not always organised correctly depending on sequence of events (might be a race condition of sorts) (iOS 10.2)

### ISSUE THREAD

**Issue by ja1lbr3akr** [angelXwind/PreferenceOrganizer2#35]
Sometimes' when opening settings for first time after respring or unlock the CydiaTweaks (section) and sometimes the SystemApps (section) gets messy or is not organized at all. 

I also noticed that if you open the settings app and swipe up quickly to go all the way to the bottom, the CydiaTweaks section wont be organized.

close/reopen settings fixes it but not if I swipe up quickly (as soon as the settings open).

edit: i6S 10.2

**Comment by angelXwind** [comment]
Closing as the issue has been fixed and will be included in the next update release.
