### ISSUE TITLE
Force-touching Wi-Fi Flipswitch in FlipControlCenter will crash Settings (iOS 10.2)

### ISSUE THREAD

**Issue by reds0ul** [angelXwind/PreferenceOrganizer2#36]
When force touching the wifi logo with flipcc it will often make settings crash right away.

iPhone 6S
iOS 10.2

**Comment by angelXwind** [comment]
Is this specific to FlipControlCenter or does it happen even without it?

**Comment by reds0ul** [comment]
I cant force touch the wifi logo unless flip control center is enabled..

**Comment by angelXwind** [comment]
Ah, I see. (Sorry, I'm not familiar with Force Touch — I don't have any devices that support it ahah)

Does this only occur if you open Settings, then press Home (backgrounding it), open some other app, then Force Touch the Wi-Fi Flipswitch?

**Comment by reds0ul** [comment]
From what I'm seeing, yes. Do you want a crash report?

**Comment by angelXwind** [comment]
Sure. Then just to confirm, does this crash _not_ occur if Settings is not open in the background?

If so, then this is considered a duplicate of issue #32 (which I initially suspected) and actually has nothing to do with Flipswitch.

**Comment by angelXwind** [comment]
Closing as the issue has been fixed and will be included in the next update release.
