### ISSUE TITLE
Organised specifiers sometimes do not show up (iOS 10.2)

### ISSUE THREAD

**Issue by pwcomp** [angelXwind/PreferenceOrganizer2#38]
when opening settings 4 custom folders don't show at all,,have to reset to correct. Not apps list shows either. Ios 10.2 iphone6s yula jb.

**Comment by angelXwind** [comment]
Custom... folders? What tweak are you using to insert custom folders (I assume you mean specifiers)?

**Comment by pwcomp** [comment]
Not explaining myself😃 the 4 folders created by prefers2 tweaks apps apple apps and system. Basically sometimes those 4 folders do not show nor the apple store app lust below.

**Comment by angelXwind** [comment]
Closing as the issue has been fixed and will be included in the next update release.
