### ISSUE TITLE
iOS 9.0.2 iPad crashes

### ISSUE THREAD

**Issue by vit9696** [angelXwind/PreferenceOrganizer2#9]
Hi,
The following line makes Preferences crash on iOS 9.0.2 iPads. I do have PreferenceLoader installed, so it is discussible who could be guilty in the issue.
https://github.com/angelXwind/PreferenceOrganizer2/blob/master/PreferenceOrganizer2.xm#L262
Guarding it with an if condition or commenting is a workaround you could temporarily push in.

What I am certain about is that the items themselves are hardly related to the crash. Almost none can be left from the complete list to get it run:
```APPLE_ACCOUNT_GROUP
STORE
ACCOUNTS_GROUP
ACCOUNT_SETTINGS
NOTES
REMINDERS
MESSAGES
FACETIME
MAPS
SAFARI
MEDIA_GROUP
MUSIC
VIDEO
Photos
GAMECENTER

**Comment by angelXwind** [comment]
You mean `TweakSpecifiers = [tweaksGroup retain];` causes iPads to crash?

**Comment by vit9696** [comment]
Agh, did I make a link to an older source file.
[specifiers removeObjectsInArray:AppleAppSpecifiers];
of course

**Comment by angelXwind** [comment]
Huh. I don't quite... understand how that could cause a crash, or why it would be specific to iPads. :/

Can you install CrashReporter and send me a syslog/crash log?

**Comment by vit9696** [comment]
Yes, sent via irc.

**Comment by vit9696** [comment]
I spent a little more time investigating this, and unfortunately found no decent way to fix it. At least I would not call catching the exceptions and ignoring them a decent idea. PSListController does even seem to store pointers to the items of specifiers array, which brings a lot of mess and makes the proper fix annoying and time-consuming to create (especially given that I do not need Apple Apps category myself). Maybe I was looking from the wrong end, and the right way is to not temper with specifiers but to hook the drawing code I don't know.

I added some workarounds to prevent it from crashing even after enabling Apple Apps category in settings by accident. Also, I think fixed the social apps/tweaks issue but this would require a change (https://github.com/rpetrich/preferenceloader/pull/1) to PreferenceLoader.
https://ghostbin.com/paste/kgz33

**Comment by OzancanKaratas** [comment]
I think you should release a new version. Also new version will provide the language support. Please release now!

**Comment by angelXwind** [comment]
@OzancanKaratas Working on updating mikoto first.

Regarding localisation support, I'll need to add a mikoto-style "Credits" section to the tweak to properly credit all contributors (English and Japanese are done in-house by myself, but you contributed the Turkish localisation, so I want to properly credit that)

**Comment by angelXwind** [comment]
Finally fixed.
